openapi: 3.0.0
info:
    title: AdoptMe API
    version: 1.0.0
    description: API para gestión de usuarios, mascotas, adopciones y sesiones
servers:
    - url: http://localhost:8080/api
      description: Servidor local de desarrollo

paths:
    /users:
        get:
            summary: Obtener todos los usuarios
            tags: [Users]
            responses:
                "200":
                    description: Lista de usuarios

    /users/{uid}:
        get:
            summary: Obtener un usuario por ID
            tags: [Users]
            parameters:
                - in: path
                  name: uid
                  schema:
                      type: string
                  required: true
                  description: ID del usuario
            responses:
                "200":
                    description: Usuario encontrado
        put:
            summary: Actualizar usuario por ID
            tags: [Users]
            parameters:
                - in: path
                  name: uid
                  schema:
                      type: string
                  required: true
                  description: ID del usuario
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/User"
            responses:
                "200":
                    description: Usuario actualizado
        delete:
            summary: Eliminar usuario por ID
            tags: [Users]
            parameters:
                - in: path
                  name: uid
                  schema:
                      type: string
                  required: true
                  description: ID del usuario
            responses:
                "200":
                    description: Usuario eliminado

    /pets:
        get:
            summary: Obtener todas las mascotas
            tags: [Pets]
            responses:
                "200":
                    description: Lista de mascotas
        post:
            summary: Crear una nueva mascota
            tags: [Pets]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Pet"
            responses:
                "201":
                    description: Mascota creada

    /pets/withimage:
        post:
            summary: Crear mascota con imagen
            tags: [Pets]
            requestBody:
                required: true
                content:
                    multipart/form-data:
                        schema:
                            type: object
                            properties:
                                image:
                                    type: string
                                    format: binary
            responses:
                "201":
                    description: Mascota con imagen creada

    /pets/{pid}:
        put:
            summary: Actualizar mascota
            tags: [Pets]
            parameters:
                - in: path
                  name: pid
                  schema:
                      type: string
                  required: true
                  description: ID de la mascota
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Pet"
            responses:
                "200":
                    description: Mascota actualizada
        delete:
            summary: Eliminar mascota
            tags: [Pets]
            parameters:
                - in: path
                  name: pid
                  schema:
                      type: string
                  required: true
                  description: ID de la mascota
            responses:
                "200":
                    description: Mascota eliminada

    /adoptions:
        get:
            summary: Obtener todas las adopciones
            tags: [Adoptions]
            responses:
                "200":
                    description: Lista de adopciones

    /adoptions/{aid}:
        get:
            summary: Obtener adopción por ID
            tags: [Adoptions]
            parameters:
                - in: path
                  name: aid
                  schema:
                      type: string
                  required: true
                  description: ID de la adopción
            responses:
                "200":
                    description: Adopción encontrada

    /adoptions/{uid}/{pid}:
        post:
            summary: Crear adopción
            tags: [Adoptions]
            parameters:
                - in: path
                  name: uid
                  schema:
                      type: string
                  required: true
                  description: ID del usuario
                - in: path
                  name: pid
                  schema:
                      type: string
                  required: true
                  description: ID de la mascota
            responses:
                "201":
                    description: Adopción creada

    /sessions/register:
        post:
            summary: Registrar usuario
            tags: [Sessions]
            responses:
                "201":
                    description: Usuario registrado
    /sessions/login:
        post:
            summary: Iniciar sesión
            tags: [Sessions]
            responses:
                "200":
                    description: Login exitoso
    /sessions/current:
        get:
            summary: Obtener usuario actual
            tags: [Sessions]
            responses:
                "200":
                    description: Usuario actual
    /sessions/unprotectedLogin:
        get:
            summary: Login sin protección
            tags: [Sessions]
            responses:
                "200":
                    description: Login sin protección
    /sessions/unprotectedCurrent:
        get:
            summary: Usuario sin protección
            tags: [Sessions]
            responses:
                "200":
                    description: Usuario sin protección

    /mocks/mockingpets:
        get:
            summary: Generar mocks de mascotas
            tags: [Mocks]
            responses:
                "200":
                    description: Lista de mocks generados
    /mocks/mockingusers:
        get:
            summary: Generar mocks de usuarios
            tags: [Mocks]
            responses:
                "200":
                    description: Lista de mocks generados
    /mocks/generateData:
        post:
            summary: Generar usuarios y mascotas en DB
            tags: [Mocks]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                users:
                                    type: integer
                                pets:
                                    type: integer
            responses:
                "200":
                    description: Datos insertados

    /loggerTest:
        get:
            summary: Generar logs de prueba
            tags: [Logger]
            responses:
                "200":
                    description: Logs generados

components:
    schemas:
        User:
            type: object
            properties:
                first_name:
                    type: string
                last_name:
                    type: string
                email:
                    type: string
                password:
                    type: string
                role:
                    type: string
        Pet:
            type: object
            properties:
                name:
                    type: string
                specie:
                    type: string
                birthDate:
                    type: string
                    format: date
                adopted:
                    type: boolean
                image:
                    type: string
        Adoption:
            type: object
            properties:
                owner:
                    type: string
                pet:
                    type: string
